### ISSUE TITLE
More Suspected Typos

### ISSUE THREAD

**Issue by KenHoffman** [rasbt/MachineLearning-QandAI-book#12]
p. 66 "$" at end that should be "." in
Figure 9.6. Illustration of a diffusion process adding and removing Gaussian
noise from an input image x. During inference, the reverse diffusion process is
used to generate a new image x starting with the noise tensor zn sampled from a
Gaussian distribution$

p. 68 Unnecessary single quote at the beginning of
‘However, the trade-off here is that sampling from diffusion models is
generally slower.

p. 104 "quickly" is not removed from the augmented sentence.
• Original sentence: “The cat quickly jumped over the lazy dog.”
• Augmented sentence: “The cat quickly jumped over the lazy
dog.” (removed “quickly”)

p. 246 "the of the model" should be "the accuracy of the model".
If the of the model trained on the adversarial validation dataset exceeds this
baseline noticeably (say 80%), then we may have a serious discrepancy issue to
investigate further.

p. 246 "interesting" should be "interested".
Overall, this is not a big issue since we are mainly interesting if there is a
strong deviation from a random baseline.

**Comment by rasbt** [comment]
Thanks a lot for sharing these, @KenHoffman, that's super helpful and I really appreciate that you took the time doing this. I addressed all of them this morning!

**Comment by KenHoffman** [comment]
You're welcome @rabst!
