### ISSUE TITLE
Typo in answer to Question 16 (A)

### ISSUE THREAD

**Issue by rama100** [rasbt/MachineLearning-QandAI-book#17]
In the answer to Question 16 (A):

"... we have an input matrix X with N tokens (rows) where each token is a d-dimensional embedding (columns). When we compute the dot product of each token embedding to each other token embedding, we multiply X^T X, which results in an N × N similarity matrix."

I think you meant to write X X^T.

**Comment by rasbt** [comment]
You are right!  I fixed it and added you to the acknowledgements. Thanks a lot for the note!
