### ISSUE TITLE
Possible typo in Q19

### ISSUE THREAD

**Issue by rama100** [rasbt/MachineLearning-QandAI-book#19]
In Q19:

"As a precision-based metric, BLEU counts how many words in the generated text (candidate text) occur in the reference text **divided by the reference text length**, where the reference text is a sample translation provided by a human, for example."

Since BLEU is a precision score, I think you meant to write "divided by the **candidate** text length".

On a related note, in Figure 19.1 step 1, 

- it should be "divided by the candidate length" (not "divided by the reference length")

- the precision should be 6/8, not 6/9.

On an unrelated note :), in Figure 19.1, step 2, I think you want the arrows pointing to "fox", not "The".

**Comment by rasbt** [comment]
Thanks so much for the note Rama. And you are right, there were couple of issues there. Just fixed it!
