### ISSUE TITLE
Typo in 23(A)

### ISSUE THREAD

**Issue by rama100** [rasbt/MachineLearning-QandAI-book#21]
"Domain shift occurs when the distribution of the input data changes, but the function that maps from input to output, remains the same."

Perhaps you meant to write something like?

"Domain shift occurs when there is covariate shift (i.e., when the distribution of the input data changes) **and** when there is concept drift (i.e., when the function that maps from input to output changes)."

BTW, I just finished the book. It is really nice - congratulations!!

**Comment by rasbt** [comment]
Thanks again for the note @rama100 . You are right, I am also just seeing that it was inconsistent with an earlier sentence

> Thus, we can think of domain shift as a combination of both covariate and concept shift.

I just updated it!
