### ISSUE TITLE
(P75) Typo 

### ISSUE THREAD

**Issue by rickiepark** [rasbt/MachineLearning-QandAI-book#25]
Hi,
Before figure 12-1, "two input and four output units" should be "four input and two output units".
Thanks! :)

**Comment by rasbt** [comment]
Thanks for the note, I can confirm, this is a typo and should be "four input and two output units"
<img width="593" alt="Screenshot 2024-07-23 at 6 53 10 AM" src="https://github.com/user-attachments/assets/ef6555f9-c4c6-4972-8c99-da3aba1ba0e1">

**Comment by rasbt** [comment]
Added it to the errata here: https://github.com/rasbt/MachineLearning-QandAI-book/blob/main/errata/README.md
