### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by rickiepark** [rasbt/MachineLearning-QandAI-book#26]
(p109) In figure 17-3, "next-sentence prediction" should be "next-word prediction".
(p121, p122) In figure 18-6 and 18-7, "Fully connected layer" box that follows "Multihead self-attention" box should be removed. 
(p129) In 2nd equation of perlexity, $\sum$ on the second line should be removed.
(p129, 132) 2nd line from the bottom, "q15-text-augment subfolder" should be "q19-evaluation-llms subfolder"

Thanks! :)

**Comment by rasbt** [comment]
Thanks for sending these along, Haesun, I really appreciate it!

> (p109) In figure 17-3, "next-sentence prediction" should be "next-word prediction".

Yes, this should definitely be "next-word prediction" or "next-token prediction"

> (p121, p122) In figure 18-6 and 18-7, "Fully connected layer" box that follows "Multihead self-attention" box should be removed.

Ah yes, this is one box too much here. Good catch!

> (p129) In 2nd equation of perlexity, $\sum$ should be removed.

Yes, in the 2nd row of the second equation, that sum shouldn't have been there. Probably a copy & paste error.

> (p129, 132) 2nd line from the bottom, "q15-text-augment subfolder" should be "q19-evaluation-llms subfolder"

Ah yes, I am not sure how q15 got here. Thanks!

I will add those to the errata and share them with the publisher for when there is the possibility for incorporating these suggestions into a reprint edition.

**Comment by rasbt** [comment]
Added them here: https://github.com/rasbt/MachineLearning-QandAI-book/tree/main/errata
