### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by rickiepark** [rasbt/MachineLearning-QandAI-book#27]
(p166) In note `stats.zscore` should be `stats.norm.ppf`.

(p180) Below Figure 27-2, 'AB', 'BC', 'AC' shoule be 'A', 'B', 'C' respectively.

(p181) In thrid paragraph, 'How about the second criterion' should be 'How about the second part of the first criterion'.

(p182) 4th and 9th line from the bottom, '>=' should be '<='. To correct the example, 'p=0.5' should be changed, for example p=0.1

(p188) In Exercise 28-1, '1(99 percent)' should be '1(100 percent)'.

(p194) 2nd line below Transfer Learning, 'pretrained target dataset' should be 'pretrained model on a target dataset'.

(p203) In Figure 30-11, 'label more training' should be 'label more data'.

Thanks!

**Comment by rasbt** [comment]
Thanks so much for sharing these @rickiepark . I checked them all, and I agree with you on all accounts. I added these to the errata for now and will implement them in a possible reprint.
