### ISSUE TITLE
Three typos

### ISSUE THREAD

**Issue by rickiepark** [rasbt/MachineLearning-QandAI-book#28]
(p212) In last sentence of 10-2 answer, "deterministic dropout" should be "random dropout".
(p217) In first and last sentences of 20-2 answer, "stateful retraining" should be "stateful training".
(p208) In last line, "example per class" is better than "example per image".

Thanks! :)

**Comment by rasbt** [comment]
Thanks again, Haesun! This is an amazing attention to detail. I added these to the errata.
