### ISSUE TITLE
BLEU - sentence-level nltk example 

### ISSUE THREAD

**Issue by d-kleine** [rasbt/MachineLearning-QandAI-book#6]
See [here](https://github.com/rasbt/MachineLearning-QandAI-book/blob/main/supplementary/q19-evaluation-llms/bleu.ipynb):

Without comments, I don't understand this code:

```python
reference =   "The quick brown fox jumped over the lazy dog"
candidate_1 = "The fast  brown fox leaped over the      dog"
candidate_2 = "The swift brown fox jumped over the lazy dog"
candidate_3 = "The swift tawny fox leaped over the indolent canine."

from nltk.translate.bleu_score import sentence_bleu

bleu_nltk_1 = sentence_bleu([reference], candidate_1, weights=[1.])
bleu_nltk_2 = sentence_bleu([reference], candidate_2, weights=[1.])
bleu_nltk_3 = sentence_bleu([reference], candidate_3, weights=[1.])

print(f"BLEU score for example 1: {bleu_nltk_1:.2f}")
print(f"BLEU score for example 2: {bleu_nltk_2:.2f}")
print(f"BLEU score for example 3: {bleu_nltk_3:.2f}")
```

I see that there is no tokenization, but for what reason did you do that and why does this sentence-level BLUE scores computation lead to different scores (when comparing it with the tokenized version before)?

**Comment by rasbt** [comment]
That's a good question! I think this may have been left there by accident. As far as I know, the sentence should be tokenized.
<img width="867" alt="Screenshot 2023-06-07 at 3 29 15 PM" src="https://github.com/rasbt/MachineLearning-QandAI-book/assets/5618407/907553be-660a-47ff-8d56-4ec4cbec88a0">
